import { Category } from "../types/menuitems";
// kalmaxi
// dorado
// sibasi
// barabuli
// soko sulgunit
// bostneuli dafaze
const R2_BASE_URL = "https://pub-85c4415b8777427885a5ec962d4969d2.r2.dev";

const img = (path: string) => `${R2_BASE_URL}${path}`;

export const menu: Category[] = [
  {
    id: "drinks",
    nameKey: "სასმელები",
    items: [
      {
        id: "raspberry-lemonade",
        nameKey: "მალინის ლიმონათი",
        descriptionKey: "სახლის ლიმონათი მალინით 11/25",
        image: img("/images (3).jpeg"),
        price: 11,
      },
      {
        id: "strawberry-lemonade",
        nameKey: "მარწყვის ლიმონათი",
        descriptionKey: "სახლის ლიმონათი მარწყვით და ლიმონით 11/25",
        image: img("/ma.webp"),
        price: 11,
      },
      {
        id: "watermelon-lemonade",
        nameKey: "საზამთროს ლიმონათი",
        descriptionKey: "ახალი საზამთროს ლიმონათი 11/25",
        image: img("/wat.jpg"),
        price: 11,
      },
      {
        id: "Natakhtari Soft Drink 0.5l",
        nameKey: "Natakhtari Soft Drink 0.5l",
        descriptionKey: "Natakhtari Soft Drink 0.5l",
        image: img("/nat.jpeg"),
        price: 10,
      },
      {
        id: "Bliss Soft Drink 1l",
        nameKey: "Bliss Soft Drink 1l",
        descriptionKey: "Bliss Soft Drink 15/25",
        image: img("/bliss.jpeg"),
        price: 25,
      },
      {
        id: "mint-lemonade",
        nameKey: "პიტნის ლიმონათი",
        descriptionKey: "გამაგრილებელი ლიმონათი პიტნით და ლიმონით 11/25",
        image: img("/mint.jpg"),
        price: 11,
      },
      {
        id: "Shalgam",
        nameKey: "Shalgam",
        descriptionKey: "Shalgam 10/20",
        image: img("/shalgam-fermented-black-carrot-juice-1-liter.jpg"),
        price: 10,
      },
      {
        id: "Ayran",
        nameKey: "Ayran",
        descriptionKey: "Ayran",
        image: img("/Ayran-recipe-500x375.webp"),
        price: 5,
      },
      {
        id: "Red bull",
        nameKey: "ენერგეტიკული სასმელი",
        image: img("/hek.jpg"),
        price: 15,
      },
      {
        id: "Coca-Cola",
        nameKey: "Soft სასმელი",
        image: img("/coke1.png"),
        price: 7,
      },
      {
        id: "Sprite",
        nameKey: "Soft სასმელი",
        image: img("/sprite.jpg"),
        price: 7,
      },
      {
        id: "Fanta",
        nameKey: "Soft სასმელი",
        image: img("/ფანტა.jpg"),
        price: 7,
      },
      {
        id: "Berni",
        nameKey: "Soft სასმელი",
        image: img("/ბერ.png"),
        price: 7,
      },
      {
        id: "Water 0.5l",
        nameKey: " სასმელი 0.5l",
        image: img("/ბახ.jpg"),
        price: 5,
      },
      {
        id: "Water 1l",
        nameKey: "სასმელი 1l",
        image: img("/ბახ.jpg"),
        price: 7,
      },
      {
        id: "Borjomi 0.5l",
        nameKey: "სასმელი borjomi 0.5l",
        image: img("/ბორჯ.jpeg"),
        price: 5,
      },
      {
        id: "Borjomi 1l",
        nameKey: "სასმელი borjomi 1l",
        image: img("/ბორჯ.jpeg"),
        price: 7,
      },
      {
        id: "Borjomi Soft Drink 0.5l Peach",
        nameKey: "სასმელი soft borjomi 1l",
        image: img("/pe.webp"),
        price: 10,
      },
      {
        id: "Borjomi Soft Drink 0.5l Tarxuna",
        nameKey: "სასმელი soft borjomi 1l",
        image: img("/ta.webp"),
        price: 10,
      },
      {
        id: "Borjomi Soft Drink 0.5l Tangerine",
        nameKey: "სასმელი soft borjomi 1l",
        image: img("/23.webp"),
        price: 10,
      },
      {
        id: "Borjomi Soft Drink 0.5l Citrus",
        nameKey: "სასმელი soft borjomi 1l",
        image: img("/213.png"),
        price: 10,
      },
      {
        id: "Bakuriani Glass Water 0.5l ",
        nameKey: "სასმელი borjomi 1l",
        image: img("/ბაკ.jpg"),
        price: 5,
      },
      {
        id: "Red bull zero",
        nameKey: "ენერგეტიკული სასმელი",
        image: img("/i.jpeg"),
        price: 12,
      },
      {
        id: "Red bull Yellow",
        nameKey: "ენერგეტიკული სასმელი",
        image: img("/red.jpg"),
        price: 12,
      },
      {
        id: "cold-coffee",
        nameKey: "ცივი ყავა",
        descriptionKey: "გამაგრილებელი ცივი ყავა ",
        image: img("/civi.jpg"),
        price: 25,
      },
      {
        id: "cold-coffee with ice cream",
        nameKey: "ცივი ყავა",
        descriptionKey: "გამაგრილებელი ცივი ყავა ნაყინით",
        image: img("/civi.jpg"),
        price: 30,
      },
      {
        id: "cappuccino",
        nameKey: "კაპუჩინო",
        descriptionKey: "ყავის სახეობა",
        image: img("/cap.jpg"),
        price: 12,
      },
      {
        id: "americano",
        nameKey: "ამერიკანო",
        descriptionKey: "ყავის სახეობა",
        image: img("/americano12.jpg"),
        price: 10,
      },
      {
        id: "latte",
        nameKey: "ლატე",
        descriptionKey: "ყავის სახეობა",
        image: img("/late.webp"),
        price: 15,
      },
      {
        id: "espresso",
        nameKey: "ესპრესო",
        descriptionKey: "ძლიერი ყავა",
        image: img("/esp.webp"),
        price: 8,
      },
    ],
    image: img("/coc.webp"),
  },

  {
    id: "sauces",
    nameKey: "სოუსები",
    items: [
      {
        id: "tyemali",
        nameKey: "ტყემალი",
        descriptionKey: "ქართული ტრადიციული სოუსი",
        image: img("/tyemali_w_h.jpeg"),
        price: 5,
      },
      {
        id: "satsebeli",
        nameKey: "საწებელი",
        descriptionKey: "ქართული ტრადიციული სოუსი",
        image: img("/satsebeli.jpeg"),
        price: 5,
      },
      {
        id: "adjika",
        nameKey: "აჯიკა",
        descriptionKey: "ცხარე ქართული სოუსი",
        image: img("/adjika.jpeg"),
        price: 5,
      },
      {
        id: "ketchup",
        nameKey: "კეტჩუპი",
        descriptionKey: "ტომატის სოუსი",
        image: img("/ketchup.jpg"),
        price: 5,
      },
      {
        id: "mayonnaise",
        nameKey: "მაიონეზი",
        descriptionKey: "კრემოვანი სოუსი",
        image: img("/maio.webp"),
        price: 5,
      },
      {
        id: "baje",
        nameKey: "ბაჟე",
        descriptionKey: "კაკლის ქართული სოუსი",
        image: img("/90.jpg"),
        price: 10,
      },
      {
        id: "barbecue-sauce",
        nameKey: "ბარბექიუს სოუსი",
        descriptionKey: "ტკბილ-შებოლილი სოუსი",
        image: img("/bbq.jpg"),
        price: 7,
      },
      {
        id: "nasharab",
        nameKey: "ნაშარაბი",
        descriptionKey: "ბროწეულის სოუსი",
        image: img("/medium.webp"),
        price: 7,
      },
    ],
    image: img("/sauce.jpeg"),
  },

  {
    id: "alcohol",
    nameKey: "ალკოჰოლური სასმელები",
    items: [
      {
        id: "chacha-silver",
        nameKey: "ჭაჭა",
        descriptionKey: "ქართული ალკოჰოლური სასმელი 10/80",
        price: 10,
        image: img("/silver.jpg"),
      },
      {
        id: "Tskriala Semi-dry",
        nameKey: "შამპანური",
        descriptionKey: "ალკოჰოლური სასმელი",
        price: 60,
        image: img("/დრყ.jpg"),
      },
      {
        id: "Tskriala Semi-sweet",
        nameKey: "შამპანური",
        descriptionKey: "ალკოჰოლური სასმელი",
        price: 60,
        image: img("/ტკბილი.jpg"),
      },
      {
        id: "Tsinandali Semi-Dry",
        nameKey: "Tsinandali",
        descriptionKey: "ალკოჰოლური სასმელი 12/60",
        price: 60,
        image: img("/წინ.jpg"),
      },
      {
        id: "Manavi Mtsvane Semi-Dry",
        nameKey: "Manavi",
        descriptionKey: "ალკოჰოლური სასმელი 12/60",
        price: 60,
        image: img("/მანავი.png"),
      },
      {
        id: "Tvishi Semi-Sweet",
        nameKey: "Tvishi",
        descriptionKey: "ალკოჰოლური სასმელი 15/75",
        price: 75,
        image: img("/ტვიში.png"),
      },
      {
        id: "Kisi Mstvane Semi-Sweet",
        nameKey: "Kisi",
        descriptionKey: "ალკოჰოლური სასმელი 12/60",
        price: 60,
        image: img("/kisi.png"),
      },
      {
        id: "Saferavi Red-Dry",
        nameKey: "Saferavi",
        descriptionKey: "ალკოჰოლური სასმელი 12/60",
        price: 60,
        image: img("/საფერავი.jpg"),
      },
      {
        id: "Kindzmarauli",
        nameKey: "kindzmarauli",
        descriptionKey: "ალკოჰოლური სასმელი 15/75",
        price: 75,
        image: img("/უნ.png"),
      },
      {
        id: "Kindzmarauli-Draft",
        nameKey: "kindzmarauli",
        descriptionKey: "ალკოჰოლური სასმელი 20/75",
        price: 20,
        image: img("/ქინძი.png"),
      },
      {
        id: "Kvantchkara",
        nameKey: "Kvantchkara",
        descriptionKey: "ალკოჰოლური სასმელი 20/120",
        price: 20,
        image: img("/xvanchkara.jpg"),
      },
      {
        id: "Manavi Mtsvane Semi-Dry Draft",
        nameKey: "Manavi",
        descriptionKey: "ალკოჰოლური სასმელი 15/40",
        price: 15,
        image: img("/მანავი.png"),
      },
      {
        id: "Tsolikauri",
        nameKey: "Colikauri",
        descriptionKey: "ალკოჰოლური სასმელი 15/40",
        price: 15,
        image: img("/col.jpg"),
      },
      {
        id: "Saferavi Red Semi-Dry",
        nameKey: "Saferavi Red Semi-Dry",
        descriptionKey: "ალკოჰოლური სასმელი 15/40",
        price: 15,
        image: img("/saferavi.jpg"),
      },
      {
        id: "Sarajisvhili 5 star",
        nameKey: "sarajishvili 5 star",
        descriptionKey: "ქართული ალკოჰოლური სასმელი 20/200",
        price: 20,
        image: img("/sar5.jpg"),
      },
      {
        id: "Sarajisvhili 3 star",
        nameKey: "sarajishvili 3 star",
        descriptionKey: "ქართული ალკოჰოლური სასმელი 15/150",
        price: 15,
        image: img("/sar3.jpg"),
      },
      {
        id: "Askaneli",
        nameKey: "Askaneli",
        descriptionKey: "ალკოჰოლური სასმელი 22/400",
        price: 22,
        image: img("/ask.jpg"),
      },
      {
        id: "White-Rome",
        nameKey: "White Rome",
        descriptionKey: "ქართული ალკოჰოლური სასმელი 15/250",
        price: 15,
        image: img("/romi.webp"),
      },
      {
        id: "Black-Rome",
        nameKey: "Black Rome",
        descriptionKey: "ქართული ალკოჰოლური სასმელი 20/250",
        price: 20,
        image: img("/rom.jpeg"),
      },
      {
        id: "Danska 1l",
        nameKey: "danska 1l",
        descriptionKey: "ალკოჰოლური სასმელი 1l",
        price: 90,
        image: img("/danskaia.jpg"),
      },
      {
        id: "Danska 0.5l",
        nameKey: "danska 0.5l",
        descriptionKey: "ალკოჰოლური სასმელი 0.5l",
        price: 70,
        image: img("/danskaia.jpg"),
      },
      {
        id: "Chacha Gold",
        nameKey: "ჭაჭა",
        descriptionKey: "ალკოჰოლური სასმელი 10/85",
        price: 85,
        image: img("/gold.jpg"),
      },
      {
        id: "Chacha Gold Glass",
        nameKey: "ჭაჭა",
        descriptionKey: "ალკოჰოლური სასმელი",
        price: 11,
        image: img("/gold.jpg"),
      },
      {
        id: "Vodka Energy",
        nameKey: "vodka energy",
        descriptionKey: " ალკოჰოლური სასმელი",
        price: 23,
        image: img("/votka.jpg"),
      },
      {
        id: "Whiskey Energy",
        nameKey: "Whiskey Energy",
        descriptionKey: " ალკოჰოლური სასმელი",
        price: 23,
        image: img("/jeki.jpg"),
      },
      {
        id: "Stroh",
        nameKey: "Stroh",
        descriptionKey: " ალკოჰოლური სასმელი",
        price: 20,
        image: img("/stroh.jpg"),
      },
      {
        id: "Tequila Blanco",
        nameKey: "Tequila Blanco",
        descriptionKey: " ალკოჰოლური სასმელი",
        price: 14,
        image: img("/blank.webp"),
      },
      {
        id: "Tequila Gold",
        nameKey: "Tequila Gold",
        descriptionKey: " ალკოჰოლური სასმელი",
        price: 14,
        image: img("/gold.webp"),
      },
      {
        id: "Baileys",
        nameKey: "Baileys",
        descriptionKey: " ალკოჰოლური სასმელი",
        price: 15,
        image: img("/baileys.jpg"),
      },
      {
        id: "Martini Rosso",
        nameKey: "Martini Rosso",
        descriptionKey: " ალკოჰოლური სასმელი",
        price: 14,
        image: img("/mart.jpg"),
      },
      {
        id: "Martini Bianco",
        nameKey: "Martini Bianco",
        descriptionKey: " ალკოჰოლური სასმელი",
        price: 14,
        image: img("/martini.jpg"),
      },
      {
        id: "Absent",
        nameKey: "Absent",
        descriptionKey: " ალკოჰოლური სასმელი",
        price: 20,
        image: img("/absent.avif"),
      },
      {
        id: "Sambuca",
        nameKey: "Sambuca",
        descriptionKey: " ალკოჰოლური სასმელი",
        price: 20,
        image: img("/sambuca.jpg"),
      },
      {
        id: "Kahlua",
        nameKey: "Kahlua",
        descriptionKey: " ალკოჰოლური სასმელი",
        price: 14,
        image: img("/kah.jpg"),
      },
      {
        id: "Gintonic",
        nameKey: "Gintonic",
        descriptionKey: " ალკოჰოლური სასმელი",
        price: 23,
        image: img("/ginto.jpg"),
      },
      {
        id: "Cuba Libre",
        nameKey: "Cuba Libre",
        descriptionKey: " ალკოჰოლური სასმელი",
        price: 23,
        image: img("/cuba.webp"),
      },
      {
        id: "Brokers",
        nameKey: "Brokers",
        descriptionKey: " ალკოჰოლური სასმელი 1l",
        price: 200,
        image: img("/broker.jpg"),
      },
      {
        id: "Long Island",
        nameKey: "Long Island energy",
        descriptionKey: " ალკოჰოლური სასმელი",
        price: 36,
        image: img("/long.jpg"),
      },
      {
        id: "Aperol Spritz",
        nameKey: "Aperol Spritz",
        descriptionKey: " ალკოჰოლური სასმელი",
        price: 30,
        image: img("/aper.jpg"),
      },
      {
        id: "Margarita",
        nameKey: "Margarita",
        descriptionKey: " ალკოჰოლური სასმელი",
        price: 25,
        image: img("/Margarita.webp"),
      },
      {
        id: "Pinacolada",
        nameKey: "Pinacolada",
        descriptionKey: " ალკოჰოლური სასმელი",
        price: 25,
        image: img("/pin.jpg"),
      },
      {
        id: "Cosmopolitane",
        nameKey: "Cosmopolitan",
        descriptionKey: " ალკოჰოლური სასმელი",
        price: 25,
        image: img("/cosmo.webp"),
      },
      {
        id: "Negroni",
        nameKey: "Negroni",
        descriptionKey: " ალკოჰოლური სასმელი",
        price: 30,
        image: img("/negr.jpg"),
      },
      {
        id: "Jager Energy",
        nameKey: "Jager Energy",
        descriptionKey: " ალკოჰოლური სასმელი",
        price: 23,
        image: img("/jager.jpg"),
      },
      {
        id: "Mojito Classic",
        nameKey: "Mohito Classic",
        descriptionKey: "არაალკოჰოლური სასმელი",
        price: 18,
        image: img("/mojito.jpg"),
      },
      {
        id: "Mojito No-alcohol",
        nameKey: "Mohito No Alcohol",
        descriptionKey: " ალკოჰოლური სასმელი",
        price: 15,
        image: img("/mojito.jpg"),
      },
      {
        id: "Milkshake",
        nameKey: "Milkshake",
        descriptionKey: " ალკოჰოლური სასმელი",
        price: 15,
        image: img("/kia.jpeg"),
      },
      {
        id: "B-52",
        nameKey: "B52",
        descriptionKey: " ალკოჰოლური სასმელი",
        price: 18,
        image: img("/b52.webp"),
      },
      {
        id: "Absolute 0.5l",
        nameKey: "აბსოლუტი",
        descriptionKey: "ვოდკა",
        price: 100,
        image: img("/baba.jpg"),
      },
      {
        id: "Absolute 1l",
        nameKey: "აბსოლუტი",
        descriptionKey: "ვოდკა",
        price: 200,
        image: img("/baba.jpg"),
      },
      {
        id: "Boudvaizer 0.33l",
        nameKey: "bouldwaizer",
        descriptionKey: "ალკოჰოლური სასმელი",
        price: 12,
        image: img("/buoweiser.jpeg"),
      },
      {
        id: "Boudvaizer 0.5l",
        nameKey: "bouldwaizer 0.5l",
        descriptionKey: "ალკოჰოლური სასმელი",
        price: 15,
        image: img("/buoweiser.jpeg"),
      },
      {
        id: "Nemiroff 0.5l",
        nameKey: "ნემიროფი",
        descriptionKey: "ალკოჰოლური სასმელი",
        price: 50,
        image: img("/nem.jpeg"),
      },
      {
        id: "Nemiroff 1l deluxe",
        nameKey: "ნემიროფი",
        descriptionKey: "ალკოჰოლური სასმელი",
        price: 100,
        image: img("/nem.jpeg"),
      },
      {
        id: "Nemiroff 1l",
        nameKey: "ნემიროფი",
        descriptionKey: "ალკოჰოლური სასმელი ხორბლის",
        price: 50,
        image: img("/nem.jpeg"),
      },
      {
        id: "Stoli Gold 0.7l",
        nameKey: "ნემიროფი",
        descriptionKey: "ალკოჰოლური სასმელი",
        price: 70,
        image: img("/nem.jpeg"),
      },
      {
        id: "Stoli Gold 1l",
        nameKey: "ნემიროფი",
        descriptionKey: "ალკოჰოლური სასმელი",
        price: 100,
        image: img("/nem.jpeg"),
      },
      {
        id: "Gobek Raki",
        nameKey: "რაქი",
        descriptionKey: "თურქული სასმელი 25/100/180/220",
        price: 25,
        image: img("/raki.webp"),
      },
      {
        id: "Efes Gold",
        nameKey: "ეფესი გოლდი",
        descriptionKey: "ალკოჰოლური სასმელი",
        price: 18,
        image: img("/ასდა.avif"),
      },
      {
        id: "Efe Gold Raki",
        nameKey: "gold raki",
        descriptionKey: "ალკოჰოლური სასმელი 30/150/240",
        price: 30,
        image: img("/efe.jpg"),
      },
      {
        id: "Jack Daniels",
        nameKey: "ჯეკ დენიელსი",
        descriptionKey: "ვისკი 20/300",
        price: 20,
        image: img("/jak.webp"),
      },
      {
        id: "chivas regal 18YO",
        nameKey: "ჩივას რეგალი",
        descriptionKey: "ვისკი 45/450",
        price: 45,
        image: img("/chiv.gif"),
      },
      {
        id: "chivas regal 12YO",
        nameKey: "ჩივას რეგალი",
        descriptionKey: "ვისკი 20/360",
        price: 20,
        image: img("/chiv.gif"),
      },
      {
        id: "John Walker ",
        nameKey: "John Walker",
        descriptionKey: "ვისკი 18/360",
        price: 18,
        image: img("/joni.jpg"),
      },
      {
        id: "John Walker Red",
        nameKey: "John Walker Red",
        descriptionKey: "ვისკი 16/320",
        price: 16,
        image: img("/labe.jpg"),
      },
      {
        id: "red-label",
        nameKey: "რედ ლეიბელი",
        descriptionKey: "ვისკი",
        price: 0,
        image: img("/sp.jpg"),
      },
      {
        id: "jameson",
        nameKey: "ჯეიმსონი",
        descriptionKey: "ვისკი 30/400",
        price: 30,
        image: img("/jame.avif"),
      },
      {
        id: "karva",
        nameKey: "ქარვა",
        descriptionKey: "ლუდი",
        price: 15,
        image: img("/carva.jpg"),
      },
      {
        id: "natakhtari",
        nameKey: "ნატახტარი",
        descriptionKey: "ლუდი",
        price: 12,
        image: img("/nat.webp"),
      },
      {
        id: "efes",
        nameKey: "ეფესი",
        descriptionKey: "ლუდი",
        price: 13,
        image: img("/efesbeer330.webp"),
      },
      {
        id: "heineken",
        nameKey: "ჰეინეკენი",
        descriptionKey: "ლუდი",
        price: 20,
        image: img("/heineken.avif"),
      },
      {
        id: "Koshken Korva",
        nameKey: "koshken",
        descriptionKey: "ალკოჰოლური სასმელი 0.5",
        price: 60,
        image: img("/koshka.avif"),
      },
      {
        id: "Koshken Korva 1l",
        nameKey: "koshken",
        descriptionKey: "ალკოჰოლური სასმელი 1",
        price: 60,
        image: img("/koshka.avif"),
      },
      {
        id: "Kirke",
        nameKey: "koshken",
        descriptionKey: "ალკოჰოლური სასმელი",
        price: 60,
        image: img("/kir.avif"),
      },
      {
        id: "estrela",
        nameKey: "estrella",
        descriptionKey: "ლუდი",
        price: 15,
        image: img("/es.jpg"),
      },
      {
        id: "Draft Beer",
        nameKey: "ჩამოსასხმელი ლუდი",
        descriptionKey: "ლუდი",
        price: 15,
        image: img("/chamoasxi.jpg"),
      },
      {
        id: "Erdinger",
        nameKey: "Erdinger",
        descriptionKey: "ლუდი",
        price: 15,
        image: img("/erd.webp"),
      },
    ],
    image: img("/alcohol.png"),
  },

  {
    id: "soups",
    nameKey: "წვნიანები",
    items: [
      {
        id: "chicken-soup",
        nameKey: "ქათმის წვნიანი",
        descriptionKey: "ქათმის ბულიონი",
        price: 15,
        image: img("/unnamed.jpg"),
      },
      {
        id: "mushroom-cream",
        nameKey: "სოკოს კრემსუპი",
        descriptionKey: "კრემოვანი სუპი",
        price: 18,
        image: img("/soup.jpg"),
      },
      {
        id: "mushroom-soup",
        nameKey: "სოკოს წვნიანი",
        descriptionKey: "სოკოს სუპი",
        price: 15,
        image: img("/sokos_wvniani.jpg"),
      },
      {
        id: "kharcho",
        nameKey: "ხარჩო",
        descriptionKey: "ქართული სუპი",
        price: 22,
        image: img("/kharchos-recepti.webp"),
      },
      {
        id: "chorba",
        nameKey: "ჩორბა",
        descriptionKey: "თურქული სუპი",
        price: 15,
        image: img("/ჩორბა.avif"),
      },
      {
        id: "yogurt-soup",
        nameKey: "მაწვნის სუპი",
        descriptionKey: "მსუბუქი სუპი",
        price: 10,
        image: img("/matsvnis-supi.jpg"),
      },
      {
        id: "akroshka",
        nameKey: "აკროშკა",
        price: 14,
        image: img("/აკ.jpg"),
      },
      {
        id: "chixirtma",
        nameKey: "ჩიხირთმა",
        descriptionKey: "მსუბუქი სუპი",
        price: 18,
        image: img("/ჩიხ.webp"),
      },
      {
        id: "xashlama",
        nameKey: "ხაშლამა",
        descriptionKey: "წვნიანი",
        price: 21,
        image: img("/ხაშლამა.jpg"),
      },
      {
        id: "uxa",
        nameKey: "უხა",
        descriptionKey: "წვნიანი",
        price: 16,
        image: img("/უხა.webp"),
      },
    ],
    image: img("/soup.jpg"),
  },

  {
    id: "salads",
    nameKey: "სალათები",
    items: [
      {
        id: "choban-salad",
        nameKey: "ჩობან სალათა",
        descriptionKey: "თურქული სალათა",
        price: 15,
        image: img("/choban.jpg"),
      },
      {
        id: "კიტრი პომიდვრის სალათა",
        nameKey: "კიტრი პომიდვრის სალათა",
        descriptionKey: "სალათა",
        image: img("/კი.jpeg"),
      },
      {
        id: "კიტრი პომიდვრის სალათა ნიგვზით",
        nameKey: "კიტრი პომიდვრის სალათა ნიგვზით",
        descriptionKey: "სალათა",
        price: 18,
        image: img("/ნიგ.jpg"),
      },
      {
        id: "მწვანე სალათა",
        nameKey: "მწვანე სალათა",
        descriptionKey: "სალათა",
        price: 15,
        image: img("/მწ.webp"),
      },
      {
        id: "kasik salata",
        nameKey: "კაში სალათა",
        descriptionKey: "სალათა",
        price: 15,
        image: img("/2006.webp"),
      },
      {
        id: "zetisxili",
        nameKey: "დაქუცმაცებული ზეთისხილი",
        descriptionKey: " სალათა",
        price: 15,
        image: img("/oliv.jpg"),
      },
      {
        id: "season-salad",
        nameKey: "სეზონური სალათა",
        descriptionKey: "ახალი ბოსტნეული",
        price: 15,
        image: img("/sezon.jpg"),
      },
      {
        id: "caesar-chicken",
        nameKey: "ცეზარის სალათა ქათმით",
        descriptionKey: "კლასიკური სალათა",
        price: 28,
        image: img("/caesar.jpg"),
      },
      {
        id: "caesar-shrimp",
        nameKey: "ცეზარის სალათა კრევეტით",
        descriptionKey: "კლასიკური სალათა",
        price: 44,
        image: img("/caes.jpeg"),
      },
      {
        id: "greek-salad",
        nameKey: "ბერძნული სალათა",
        descriptionKey: "კლასიკური სალათა",
        price: 44,
        image: img("/grik.jpg"),
      },
    ],
    image: img("/salad.jpg"),
  },

  {
    id: "cold-meals",
    nameKey: "ცივი კერძები",
    items: [
      {
        id: "green-bouqet",
        nameKey: "მწვანილის თაიგული",
        price: 15,
        image: img("/ნწ.jpeg"),
      },
      {
        id: "badrijani",
        nameKey: "ბადრიჯანი ნიგვზით",
        price: 16,
        image: img("/nigvziani-badrijani.jpg"),
      },
      {
        id: "turkish-cheese",
        nameKey: "თურქული ყველი",
        price: 16,
        image: img("/turkche.jpg"),
      },
      {
        id: "georgian-cheese",
        nameKey: "სულგუნი ყველი",
        price: 16,
        image: img("/სულგუნი.jpg"),
      },
      {
        id: "smoked-cheese",
        nameKey: "შებოლილი ყველი",
        price: 16,
        image: img("/შებოლილი.jpg"),
      },
      {
        id: "cheese-asort",
        nameKey: "ყველის ასორტი",
        price: 22,
        image: img("/yveli.webp"),
      },
      {
        id: "pickles-asort",
        nameKey: "მჟავის ასორტი",
        price: 12,
        image: img("/pickles-1.webp"),
      },
      {
        id: "phkhali-asort",
        nameKey: "ფხალის ასორტი",
        price: 28,
        image: img("/unnamed (2).jpg"),
      },
      {
        id: "kisir",
        nameKey: "კისირი",
        price: 15,
        image: img("/kisir.jpg"),
      },
      {
        id: "carrot-yogurt",
        nameKey: "სტაფილოს იოგურტი",
        price: 15,
        image: img("/kar.jpg"),
      },
      {
        id: "europe-cheese",
        nameKey: "ევროპული ყველის ასორტი",
        price: 45,
        image: img("/yvel.webp"),
      },
    ],
    image: img("/assorts.avif"),
  },

  {
    id: "meat",
    nameKey: "ხორცეული",
    items: [
      {
        id: "liver-bbq",
        nameKey: "ჯიგრის მწვადი",
        price: 25,
        image: img("/liver.jpg"),
      },
      {
        id: "chkmeruli",
        nameKey: "ჩქმერული",
        price: 48,
        image: img("/32.png"),
      },
      {
        id: "kagit kebab",
        nameKey: "ქაღალდის ქაბაბი",
        price: 30,
        image: img("/likas.jpg"),
      },
      {
        id: "kazbasi kebab",
        nameKey: "ბატის თავის ქაბაბი",
        price: 40,
        image: img("/kaz.jpeg"),
      },
      {
        id: "sac kavurma",
        nameKey: "საკ შეწვა",
        price: 35,
        image: img("/sac.webp"),
      },
      {
        id: "tepsi kebab",
        nameKey: "უჯრა ქაბაბი",
        price: 30,
        image: img("/kasd.jpeg"),
      },
      {
        id: "sarma beyti",
        nameKey: "სარმას კუპლეტი",
        price: 35,
        image: img("/sarma.jpeg"),
      },
      {
        id: "lamb-ribs",
        nameKey: "ხბოს ნეკნი",
        price: 40,
        image: img("/lamb.jpg"),
      },
      {
        id: "Sheep-BBQ",
        nameKey: "ცხვრის მწვადი",
        price: 40,
        image: img("/393.jpg"),
      },
      {
        id: "lamb-ribs",
        nameKey: "ცხვრის ნეკნი",
        price: 40,
        image: img("/lamb1.jpg"),
      },
      {
        id: "adana-kebab",
        nameKey: "ადანა ქაბაბი",
        price: 35,
        image: img("/adana.webp"),
      },
      {
        id: "chicken-bbq",
        nameKey: "ქათმის მწვადი",
        price: 30,
        image: img("/მწვადი.png"),
      },
      {
        id: "chicken-wings",
        nameKey: "ქათმის ფრთები",
        price: 30,
        image: img("/asda.webp"),
      },
      {
        id: "smoked-lamb",
        nameKey: "ხბოს ჩაშუშული",
        price: 32,
        image: img("/images.jpeg"),
      },
      {
        id: "family-lamb",
        nameKey: "ხბოს ოჯახური",
        price: 28,
        image: img("/ხბოჯახური.png"),
      },
      {
        id: "tabaka-chick",
        nameKey: "ტაბაკა წიწილა",
        price: 27,
        image: img("/chabaka.webp"),
      },
      {
        id: "madam-bouvar",
        nameKey: "მადამ ბოვარი",
        price: 30,
        image: img("/madam-bovaris-recepti.webp"),
      },
      {
        id: "steak",
        nameKey: "სტეიკი სოკოს სოუსით",
        price: 35,
        image: img("/steak.jpg"),
      },
      {
        id: "Belen tava",
        nameKey: "ბელენ ტრეი",
        price: 40,
        image: img("/belen.jpeg"),
      },
      {
        id: "ribs-ajika",
        nameKey: "ნეკნი აჯიკაში",
        price: 80,
        image: img("/აჯიკა.webp"),
      },
      {
        id: "family-chicken",
        nameKey: "ოჯახური ქათმის",
        price: 20,
        image: img("/ojakhuri.jpg"),
      },
      {
        id: "sausage-desk",
        nameKey: "სოსისების დაფა",
        price: 70,
        image: img("/7.jpg"),
      },
      {
        id: "liver-withsauce",
        nameKey: "ღვიძლი საფანის სოუსით",
        price: 20,
        image: img("/bjih.jpg"),
      },
      {
        id: "kiev-coutlet",
        nameKey: "კიევური კატლეტი ფრით ან პიურით",
        price: 35,
        image: img("/kiev.webp"),
      },
      {
        id: "mixed-grill",
        nameKey: "შერეული გრილი",
        descriptionKey: "ქათამი + ხბო + ქაბაბი",
        price: 80,
        image: img(
          "/assorted-mix-grills-with-chicken-tikka-beef-kabab-mutton-kebab-wings-boti-malai-chop-shish-tawook-served-dish-isolated-background-top-view-arabic-food_689047-4724.avif",
        ),
      },
      {
        id: "kebab-pan",
        nameKey: "ჩაშლილი ქაბაბი კეცზე",
        price: 35,
        image: img("/kebab.webp"),
      },
    ],
    image: img("/meat.jpg"),
  },

  {
    id: "garnir",
    nameKey: "სნექები",
    items: [
      {
        id: "mashed potatoes",
        nameKey: "პიურე",
        price: 10,
        image: img("/pou.jpg"),
      },
      {
        id: "french-fries",
        nameKey: "ფრი",
        price: 15,
        image: img("/fries.jpg"),
      },
      {
        id: "mexican",
        nameKey: "მექსიკური კარტოფილი",
        price: 15,
        image: img("/kartoili.jpg"),
      },
      {
        id: "icli kofte",
        nameKey: "იჩლი კოფტე",
        price: 10,
        image: img("/images22.jpeg"),
      },
    ],
    image: img("/fries.jpg"),
  },

  {
    id: "pastry",
    nameKey: "ცომეული",
    items: [
      {
        id: "imerian-xaxhapuri",
        nameKey: "იმერული ხაჭაპური",
        price: 25,
        image: img("/იმერული.webp"),
      },
      {
        id: "Pizza Margarita",
        nameKey: "Pizza Margarita",
        price: 25,
        image: img("/PIZZA-MARGHERITA.jpg"),
      },
      {
        id: "Pizza Mix",
        nameKey: "Pizza Mix",
        price: 30,
        image: img("/sliced-pizza.jpg"),
      },
      {
        id: "Pizza Pepperoni",
        nameKey: "Pizza Pepperoni",
        price: 30,
        image: img("/Quick-and-Easy-Pepperoni-Pizza-700x700.jpeg"),
      },
      {
        id: "Pizza Vegeretarian",
        nameKey: "Pizza Vegeretarian",
        price: 25,
        image: img("/kaio.jpeg"),
      },
      {
        id: "Pizza Lahmanjun",
        nameKey: "Pizza Lahmanjun",
        price: 15,
        image: img("/lahma.jpeg"),
      },
      {
        id: "Megrelian-Xachapuri",
        nameKey: "მეგრული ხაჭაპური",
        price: 28,
        image: img("/მეგ.webp"),
      },
      {
        id: "Royal Khachapuri",
        nameKey: "სამეფო",
        price: 34,
        image: img("/king.jpg"),
      },
      {
        id: "adjarian",
        nameKey: "აჭარული ",
        price: 23,
        image: img("/adjaruli+khachapuri.webp"),
      },
      {
        id: "mchadi",
        nameKey: "მჭადი ",
        price: 10,
        image: img("/images (2).jpeg"),
      },
      {
        id: "lobiani",
        nameKey: "ლობიანი ",
        price: 18,
        image: img("/lobiani-gnta.webp"),
      },
    ],
    image: img("/xach.jpg"),
  },

  {
    id: "seafood",
    nameKey: "თევზეულობა",
    items: [
      {
        id: "Barabulka",
        nameKey: "Barabulka",
        price: 35,
        image: img("/bar.webp"),
      },
      {
        id: "Sibasi",
        nameKey: "sibasi",
        price: 48,
        image: img("/sibas.jpg"),
      },
      {
        id: "kalmaxi",
        nameKey: "კალმახი",
        price: 25,
        image: img("/kiki.jpg"),
      },
      {
        id: "Cooked Kalmaxi",
        nameKey: "კალმახი",
        price: 25,
        image: img("/sewva.jpg"),
      },
      {
        id: "Dorado",
        nameKey: "დორადო",
        price: 55,
        image: img("/download (1).jpeg"),
      },
      {
        id: "fish-desk",
        nameKey: "ზღვის პროდუქტების დაფა",
        price: 190,
        image: img("/desk-fish.jpg"),
      },
      {
        id: "shrimp",
        nameKey: "კრევეტი",
        price: 40,
        image: img("/sh.jpg"),
      },
      {
        id: "kalmari",
        nameKey: "კალმარი",
        price: 35,
        image: img("/kalm.jpg"),
      },
    ],
    image: img("/shrimps.jpg"),
  },

  {
    id: "desserts",
    nameKey: "დესერტები",
    items: [
      {
        id: "fruit-asort",
        nameKey: "ხილის ასორტი",
        price: 20,
        image: img("/fara.jpg"),
      },
      {
        id: "watermelon-melon",
        nameKey: "ხილის ასორტი",
        price: 30,
        image: img("/kala.jpeg"),
      },
      {
        id: "Kurnefe",
        nameKey: "კურნეფე",
        price: 25,
        image: img("/kunefe.jpg"),
      },
      {
        id: "ნაყინი",
        nameKey: "დესერტი",
        price: 15,
        image: img("/nayini.jpg"),
      },
      {
        id: "ხილის ასორტი დიდი",
        nameKey: "დესერტი",
        price: 45,
        image: img("/asort.jpg"),
      },
      {
        id: "ხილის ასორტი პატარა",
        nameKey: "დესერტი",
        price: 25,
        image: img("/asort.jpg"),
      },
      {
        id: "Cheese cake",
        nameKey: "დესერტი",
        price: 15,
        image: img("/ch.jpeg"),
      },
      {
        id: "Tiramisu",
        nameKey: "tiramisu",
        price: 15,
        image: img("/tir.jpg"),
      },
      {
        id: "Baklava 3pcs",
        nameKey: "baklava",
        price: 25,
        image: img("/baki.jpeg"),
      },
      {
        id: "Magnolia",
        nameKey: "magnolia",
        price: 15,
        image: img("/mag.jpeg"),
      },
    ],
    image: img("/kunefe.jpg"),
  },

  {
    id: "meze",
    nameKey: "აპეტაიზერი",
    items: [
      {
        id: "orshtorvis-plate",
        nameKey: "ორშტორვის თეფში",
        price: 25,
        image: img("/images (1).jpeg"),
      },
      {
        id: "atom",
        nameKey: "ატომი",
        price: 15,
        image: img("/atom.webp"),
      },
      {
        id: "cacik",
        nameKey: "ჯაჯიკი",
        price: 15,
        image: img("/caca.jpg"),
      },
      {
        id: "acili ezme",
        nameKey: "აჯილი ეზმე",
        price: 15,
        image: img("/acili.jpg"),
      },
      {
        id: "strained yougurt",
        nameKey: "გაფილტრული იოგურტი",
        price: 15,
        image: img("/str.jpg"),
      },
      {
        id: "aleppo homs",
        nameKey: "ალეპო ჰომს",
        price: 15,
        image: img("/allepo.webp"),
      },
      {
        id: "hummus with olive oil",
        nameKey: "ჰუმუსი ზეითუნის ზეთით",
        price: 15,
        image: img("/hum.jpg"),
      },
      {
        id: "hummus with butter",
        nameKey: "ჰუმუსი კარაქით",
        price: 20,
        image: img("/humb.jpg"),
      },
      {
        id: "alinazik",
        nameKey: "ალინაზიკი",
        price: 20,
        image: img("/ali.jpeg"),
      },
      {
        id: "thyme salad zaatar",
        nameKey: "თიმის სალათა",
        price: 20,
        image: img("/ზატ.jpeg"),
      },
      {
        id: "Babagannuc",
        nameKey: "ბაბაგანუჩი",
        price: 15,
        image: img("/ბაბა.webp"),
      },
      {
        id: "eggplant yogurt",
        nameKey: "ბადრიჯნის იოგურტი",
        price: 15,
        image: img("/egg.jpg"),
      },
      {
        id: "olive salad",
        nameKey: "ზეთის ხილის სალათა",
        price: 15,
        image: img("/oli.jpeg"),
      },
      {
        id: "pepper yogurt",
        nameKey: "წიწაკის იოგურტი",
        price: 15,
        image: img("/images5.jpeg"),
      },
      {
        id: "cig kofte",
        nameKey: "უმი ხორცის ბურთულები",
        price: 25,
        image: img("/cig.jpg"),
      },
    ],
    image: img("/meze.jpeg"),
  },

  {
    id: "sefme-kavalte",
    nameKey: "საუზმე",
    items: [],
    image: img("/sauzme.webp"),
  },
];
