import { Category } from "../types/menuitems";
// kalmaxi
// dorado
// sibasi
// barabuli
// soko sulgunit
// bostneuli dafaze

export const menu: Category[] = [
  {
    id: "drinks",
    nameKey: "სასმელები",
    items: [
      {
        id: "raspberry-lemonade",
        nameKey: "მალინის ლიმონათი",
        descriptionKey: "სახლის ლიმონათი მალინით 11/25",
        image: "/images (3).jpeg",
        price: 11,
      },
      {
        id: "strawberry-lemonade",
        nameKey: "მარწყვის ლიმონათი",
        descriptionKey: "სახლის ლიმონათი მარწყვით და ლიმონით 11/25",
        image: "/ma.webp",
        price: 11,
      },
      {
        id: "watermelon-lemonade",
        nameKey: "საზამთროს ლიმონათი",
        descriptionKey: "ახალი საზამთროს ლიმონათი 11/25",
        image: "/wat.jpg",
        price: 11,
      },
      {
        id: "Natakhtari Soft Drink 0.5l",
        nameKey: "Natakhtari Soft Drink 0.5l",
        descriptionKey: "Natakhtari Soft Drink 0.5l",
        image: "/nat.jpeg",
        price: 10,
      },
      {
        id: "Bliss Soft Drink 1l",
        nameKey: "Bliss Soft Drink 1l",
        descriptionKey: "Bliss Soft Drink 15/25",
        image: "/bliss.jpeg",
        price: 25,
      },
      {
        id: "mint-lemonade",
        nameKey: "პიტნის ლიმონათი",
        descriptionKey: "გამაგრილებელი ლიმონათი პიტნით და ლიმონით 11/25",
        image: "/mint.jpg",
        price: 11,
      },
      {
        id: "Shalgam",
        nameKey: "Shalgam",
        descriptionKey: "Shalgam 10/20",
        image: "/shalgam-fermented-black-carrot-juice-1-liter.jpg",
        price: 10,
      },
      {
        id: "Ayran",
        nameKey: "Ayran",
        descriptionKey: "Ayran",
        image: "/Ayran-recipe-500x375.webp",
        price: 5,
      },
      {
        id: "Red bull",
        nameKey: "ენერგეტიკული სასმელი",
        image: "/hek.jpg",
        price: 15,
      },
      {
        id: "Coca-Cola",
        nameKey: "Soft სასმელი",
        image: "/coke1.png",
        price: 7,
      },
      {
        id: "Sprite",
        nameKey: "Soft სასმელი",
        image: "/sprite.jpg",
        price: 7,
      },
      {
        id: "Fanta",
        nameKey: "Soft სასმელი",
        image: "/ფანტა.jpg",
        price: 7,
      },
      {
        id: "Berni",
        nameKey: "Soft სასმელი",
        image: "/ბერ.png",
        price: 7,
      },
      {
        id: "Water 0.5l",
        nameKey: " სასმელი 0.5l",
        image: "/ბახ.jpg",
        price: 5,
      },
      {
        id: "Water 1l",
        nameKey: "სასმელი 1l",
        image: "/ბახ.jpg",
        price: 7,
      },
      {
        id: "Borjomi 0.5l",
        nameKey: "სასმელი borjomi 0.5l",
        image: "/ბორჯ.jpeg",
        price: 5,
      },
      {
        id: "Borjomi 1l",
        nameKey: "სასმელი borjomi 1l",
        image: "/ბორჯ.jpeg",
        price: 7,
      },
      {
        id: "Borjomi Soft Drink 0.5l Peach",
        nameKey: "სასმელი soft borjomi 1l",
        image: "/pe.webp",
        price: 10,
      },
      {
        id: "Borjomi Soft Drink 0.5l Tarxuna",
        nameKey: "სასმელი soft borjomi 1l",
        image: "/ta.webp",
        price: 10,
      },
      {
        id: "Borjomi Soft Drink 0.5l Tangerine",
        nameKey: "სასმელი soft borjomi 1l",
        image: "/23.webp",
        price: 10,
      },
      {
        id: "Borjomi Soft Drink 0.5l Citrus",
        nameKey: "სასმელი soft borjomi 1l",
        image: "/213.png",
        price: 10,
      },
      {
        id: "Bakuriani Glass Water 0.5l ",
        nameKey: "სასმელი borjomi 1l",
        image: "/ბაკ.jpg",
        price: 5,
      },
      {
        id: "Red bull zero",
        nameKey: "ენერგეტიკული სასმელი",
        image: "/i.jpeg",
        price: 12,
      },
      {
        id: "Red bull Yellow",
        nameKey: "ენერგეტიკული სასმელი",
        image: "/red.jpg",
        price: 12,
      },

      {
        id: "cold-coffee",
        nameKey: "ცივი ყავა",
        descriptionKey: "გამაგრილებელი ცივი ყავა ",
        image: "/civi.jpg",
        price: 25,
      },
      {
        id: "cold-coffee with ice cream",
        nameKey: "ცივი ყავა",
        descriptionKey: "გამაგრილებელი ცივი ყავა ნაყინით",
        image: "/civi.jpg",
        price: 30,
      },
      {
        id: "cappuccino",
        nameKey: "კაპუჩინო",
        descriptionKey: "ყავის სახეობა",
        image: "/cap.jpg",
        price: 12,
      },
      {
        id: "americano",
        nameKey: "ამერიკანო",
        descriptionKey: "ყავის სახეობა",
        image: "/americano12.jpg",
        price: 10,
      },
      {
        id: "latte",
        nameKey: "ლატე",
        descriptionKey: "ყავის სახეობა",
        image: "/late.webp",
        price: 15,
      },
      {
        id: "espresso",
        nameKey: "ესპრესო",
        descriptionKey: "ძლიერი ყავა",
        image: "/esp.webp",
        price: 8,
      },
    ],
    image: "/coc.webp",
  },

  {
    id: "sauces",
    nameKey: "სოუსები",
    items: [
      {
        id: "tyemali",
        nameKey: "ტყემალი",
        descriptionKey: "ქართული ტრადიციული სოუსი",
        image: "/tyemali_w_h.jpeg",
        price: 5,
      },
      {
        id: "satsebeli",
        nameKey: "საწებელი",
        descriptionKey: "ქართული ტრადიციული სოუსი",
        image: "/satsebeli.jpeg",
        price: 5,
      },
      {
        id: "adjika",
        nameKey: "აჯიკა",
        descriptionKey: "ცხარე ქართული სოუსი",
        image: "/adjika.jpeg",
        price: 5,
      },
      {
        id: "ketchup",
        nameKey: "კეტჩუპი",
        descriptionKey: "ტომატის სოუსი",
        image: "/ketchup.jpg",
        price: 5,
      },
      {
        id: "mayonnaise",
        nameKey: "მაიონეზი",
        descriptionKey: "კრემოვანი სოუსი",
        image: "/maio.webp",
        price: 5,
      },
      {
        id: "baje",
        nameKey: "ბაჟე",
        descriptionKey: "კაკლის ქართული სოუსი",
        image: "/90.jpg",
        price: 10,
      },
      {
        id: "barbecue-sauce",
        nameKey: "ბარბექიუს სოუსი",
        descriptionKey: "ტკბილ-შებოლილი სოუსი",
        image: "/bbq.jpg",
        price: 7,
      },
      {
        id: "nasharab",
        nameKey: "ნაშარაბი",
        descriptionKey: "ბროწეულის სოუსი",
        image: "/medium.webp",
        price: 7,
      },
    ],
    image: "/sauce.jpeg",
  },

  {
    id: "alcohol",
    nameKey: "ალკოჰოლური სასმელები",
    items: [
      {
        id: "chacha-silver",
        nameKey: "ჭაჭა",
        descriptionKey: "ქართული ალკოჰოლური სასმელი 10/80",
        price: 10,
        image: "/silver.jpg",
      },
      {
        id: "Tskriala Semi-dry",
        nameKey: "შამპანური",
        descriptionKey: "ალკოჰოლური სასმელი",
        price: 60,
        image: "/დრყ.jpg",
      },
      {
        id: "Tskriala Semi-sweet",
        nameKey: "შამპანური",
        descriptionKey: "ალკოჰოლური სასმელი",
        price: 60,
        image: "/ტკბილი.jpg",
      },
      {
        id: "Tsinandali Semi-Dry",
        nameKey: "Tsinandali",
        descriptionKey: "ალკოჰოლური სასმელი 12/60",
        price: 60,
        image: "/წინ.jpg",
      },
      {
        id: "Manavi Mtsvane Semi-Dry",
        nameKey: "Manavi",
        descriptionKey: "ალკოჰოლური სასმელი 12/60",
        price: 60,
        image: "/მანავი.png",
      },

      {
        id: "Tvishi Semi-Sweet",
        nameKey: "Tvishi",
        descriptionKey: "ალკოჰოლური სასმელი 15/75",
        price: 75,
        image: "/ტვიში.png",
      },
      {
        id: "Kisi Mstvane Semi-Sweet",
        nameKey: "Kisi",
        descriptionKey: "ალკოჰოლური სასმელი 12/60",
        price: 60,
        image: "/kisi.png",
      },
      {
        id: "Saferavi Red-Dry",
        nameKey: "Saferavi",
        descriptionKey: "ალკოჰოლური სასმელი 12/60",
        price: 60,
        image: "/საფერავი.jpg",
      },
      {
        id: "Kindzmarauli",
        nameKey: "kindzmarauli",
        descriptionKey: "ალკოჰოლური სასმელი 15/75",
        price: 75,
        image: "/უნ.png",
      },
      {
        id: "Kindzmarauli-Draft",
        nameKey: "kindzmarauli",
        descriptionKey: "ალკოჰოლური სასმელი 20/75",
        price: 20,
        image: "/ქინძი.png",
      },
      {
        id: "Kvantchkara",
        nameKey: "Kvantchkara",
        descriptionKey: "ალკოჰოლური სასმელი 20/120",
        price: 20,
        image: "/xvanchkara.jpg",
      },
      {
        id: "Manavi Mtsvane Semi-Dry Draft",
        nameKey: "Manavi",
        descriptionKey: "ალკოჰოლური სასმელი 15/40",
        price: 15,
        image: "/მანავი.png",
      },
      {
        id: "Tsolikauri",
        nameKey: "Colikauri",
        descriptionKey: "ალკოჰოლური სასმელი 15/40",
        price: 15,
        image: "/col.jpg",
      },
      {
        id: "Saferavi Red Semi-Dry",
        nameKey: "Saferavi Red Semi-Dry",
        descriptionKey: "ალკოჰოლური სასმელი 15/40",
        price: 15,
        image: "/saferavi.jpg",
      },

      {
        id: "Sarajisvhili 5 star",
        nameKey: "sarajishvili 5 star",
        descriptionKey: "ქართული ალკოჰოლური სასმელი 20/200",
        price: 20,
        image: "/sar5.jpg",
      },
      {
        id: "Sarajisvhili 3 star",
        nameKey: "sarajishvili 3 star",
        descriptionKey: "ქართული ალკოჰოლური სასმელი 15/150",
        price: 15,
        image: "/sar3.jpg",
      },
      {
        id: "Askaneli",
        nameKey: "Askaneli",
        descriptionKey: "ალკოჰოლური სასმელი 22/400",
        price: 22,
        image: "/ask.jpg",
      },
      {
        id: "White-Rome",
        nameKey: "White Rome",
        descriptionKey: "ქართული ალკოჰოლური სასმელი 15/250",
        price: 15,
        image: "/romi.webp",
      },
      {
        id: "Black-Rome",
        nameKey: "Black Rome",
        descriptionKey: "ქართული ალკოჰოლური სასმელი 20/250",
        price: 20,
        image: "/rom.jpeg",
      },
      {
        id: "Danska 1l",
        nameKey: "danska 1l",
        descriptionKey: "ალკოჰოლური სასმელი 1l",
        price: 90,
        image: "/danskaia.jpg",
      },
      {
        id: "Danska 0.5l",
        nameKey: "danska 0.5l",
        descriptionKey: "ალკოჰოლური სასმელი 0.5l",
        price: 70,
        image: "/danskaia.jpg",
      },
      {
        id: "Chacha Gold",
        nameKey: "ჭაჭა",
        descriptionKey: "ალკოჰოლური სასმელი 10/85",
        price: 85,
        image: "/gold.jpg",
      },
      {
        id: "Chacha Gold Glass",
        nameKey: "ჭაჭა",
        descriptionKey: "ალკოჰოლური სასმელი",
        price: 11,
        image: "/gold.jpg",
      },
      {
        id: "Vodka Energy",
        nameKey: "vodka energy",
        descriptionKey: " ალკოჰოლური სასმელი",
        price: 23,
        image: "/votka.jpg",
      },
      {
        id: "Whiskey Energy",
        nameKey: "Whiskey Energy",
        descriptionKey: " ალკოჰოლური სასმელი",
        price: 23,
        image: "/jeki.jpg",
      },
      {
        id: "Stroh",
        nameKey: "Stroh",
        descriptionKey: " ალკოჰოლური სასმელი",
        price: 20,
        image: "/stroh.jpg",
      },
      {
        id: "Tequila Blanco",
        nameKey: "Tequila Blanco",
        descriptionKey: " ალკოჰოლური სასმელი",
        price: 14,
        image: "/blank.webp",
      },
      {
        id: "Tequila Gold",
        nameKey: "Tequila Gold",
        descriptionKey: " ალკოჰოლური სასმელი",
        price: 14,
        image: "/gold.webp",
      },
      {
        id: "Baileys",
        nameKey: "Baileys",
        descriptionKey: " ალკოჰოლური სასმელი",
        price: 15,
        image: "/baileys.jpg",
      },
      {
        id: "Martini Rosso",
        nameKey: "Martini Rosso",
        descriptionKey: " ალკოჰოლური სასმელი",
        price: 14,
        image: "/mart.jpg",
      },
      {
        id: "Martini Bianco",
        nameKey: "Martini Bianco",
        descriptionKey: " ალკოჰოლური სასმელი",
        price: 14,
        image: "/martini.jpg",
      },
      {
        id: "Absent",
        nameKey: "Absent",
        descriptionKey: " ალკოჰოლური სასმელი",
        price: 20,
        image: "/absent.avif",
      },
      {
        id: "Sambuca",
        nameKey: "Sambuca",
        descriptionKey: " ალკოჰოლური სასმელი",
        price: 20,
        image: "/sambuca.jpg",
      },
      {
        id: "Kahlua",
        nameKey: "Kahlua",
        descriptionKey: " ალკოჰოლური სასმელი",
        price: 14,
        image: "/kah.jpg",
      },
      {
        id: "Gintonic",
        nameKey: "Gintonic",
        descriptionKey: " ალკოჰოლური სასმელი",
        price: 23,
        image: "/ginto.jpg",
      },
      {
        id: "Cuba Libre",
        nameKey: "Cuba Libre",
        descriptionKey: " ალკოჰოლური სასმელი",
        price: 23,
        image: "/cuba.webp",
      },
      {
        id: "Brokers",
        nameKey: "Brokers",
        descriptionKey: " ალკოჰოლური სასმელი 1l",
        price: 200,
        image: "/broker.jpg",
      },
      {
        id: "Long Island",
        nameKey: "Long Island energy",
        descriptionKey: " ალკოჰოლური სასმელი",
        price: 36,
        image: "/long.jpg",
      },
      {
        id: "Aperol Spritz",
        nameKey: "Aperol Spritz",
        descriptionKey: " ალკოჰოლური სასმელი",
        price: 30,
        image: "/aper.jpg",
      },
      {
        id: "Margarita",
        nameKey: "Margarita",
        descriptionKey: " ალკოჰოლური სასმელი",
        price: 25,
        image: "/Margarita.webp",
      },
      {
        id: "Pinacolada",
        nameKey: "Pinacolada",
        descriptionKey: " ალკოჰოლური სასმელი",
        price: 25,
        image: "/pin.jpg",
      },
      {
        id: "Cosmopolitane",
        nameKey: "Cosmopolitan",
        descriptionKey: " ალკოჰოლური სასმელი",
        price: 25,
        image: "/cosmo.webp",
      },
      {
        id: "Negroni",
        nameKey: "Negroni",
        descriptionKey: " ალკოჰოლური სასმელი",
        price: 30,
        image: "/negr.jpg",
      },
      {
        id: "Jager Energy",
        nameKey: "Jager Energy",
        descriptionKey: " ალკოჰოლური სასმელი",
        price: 23,
        image: "/jager.jpg",
      },
      {
        id: "Mojito Classic",
        nameKey: "Mohito Classic",
        descriptionKey: "არაალკოჰოლური სასმელი",
        price: 18,
        image: "/mojito.jpg",
      },
      {
        id: "Mojito No-alcohol",
        nameKey: "Mohito No Alcohol",
        descriptionKey: " ალკოჰოლური სასმელი",
        price: 15,
        image: "/mojito.jpg",
      },
      {
        id: "Milkshake",
        nameKey: "Milkshake",
        descriptionKey: " ალკოჰოლური სასმელი",
        price: 15,
        image: "/kia.jpeg",
      },
      {
        id: "B-52",
        nameKey: "B52",
        descriptionKey: " ალკოჰოლური სასმელი",
        price: 18,
        image: "/b52.webp",
      },
      {
        id: "Absolute 0.5l",
        nameKey: "აბსოლუტი",
        descriptionKey: "ვოდკა",
        price: 100,
        image: "/baba.jpg",
      },
      {
        id: "Absolute 1l",
        nameKey: "აბსოლუტი",
        descriptionKey: "ვოდკა",
        price: 200,
        image: "/baba.jpg",
      },
      {
        id: "Boudvaizer 0.33l",
        nameKey: "bouldwaizer",
        descriptionKey: "ალკოჰოლური სასმელი",
        price: 12,
        image: "/buoweiser.jpeg",
      },
      {
        id: "Boudvaizer 0.5l",
        nameKey: "bouldwaizer 0.5l",
        descriptionKey: "ალკოჰოლური სასმელი",
        price: 15,
        image: "/buoweiser.jpeg",
      },
      {
        id: "Nemiroff 0.5l",
        nameKey: "ნემიროფი",
        descriptionKey: "ალკოჰოლური სასმელი",
        price: 50,
        image: "/nem.jpeg",
      },
      {
        id: "Nemiroff 1l deluxe",
        nameKey: "ნემიროფი",
        descriptionKey: "ალკოჰოლური სასმელი",
        price: 100,
        image: "/nem.jpeg",
      },
      {
        id: "Nemiroff 1l",
        nameKey: "ნემიროფი",
        descriptionKey: "ალკოჰოლური სასმელი ხორბლის",
        price: 50,
        image: "/nem.jpeg",
      },
      {
        id: "Stoli Gold 0.7l",
        nameKey: "ნემიროფი",
        descriptionKey: "ალკოჰოლური სასმელი",
        price: 70,
        image: "/nem.jpeg",
      },
      {
        id: "Stoli Gold 1l",
        nameKey: "ნემიროფი",
        descriptionKey: "ალკოჰოლური სასმელი",
        price: 100,
        image: "/nem.jpeg",
      },

      {
        id: "Gobek Raki",
        nameKey: "რაქი",
        descriptionKey: "თურქული სასმელი 25/100/180/220",
        price: 25,
        image: "/raki.webp",
      },
      {
        id: "Efes Gold",
        nameKey: "ეფესი გოლდი",
        descriptionKey: "ალკოჰოლური სასმელი",
        price: 18,
        image: "/ასდა.avif",
      },
      {
        id: "Efe Gold Raki",
        nameKey: "gold raki",
        descriptionKey: "ალკოჰოლური სასმელი 30/150/240",
        price: 30,
        image: "/efe.jpg",
      },
      {
        id: "Jack Daniels",
        nameKey: "ჯეკ დენიელსი",
        descriptionKey: "ვისკი 20/300",
        price: 20,
        image: "/jak.webp",
      },
      {
        id: "chivas regal 18YO",
        nameKey: "ჩივას რეგალი",
        descriptionKey: "ვისკი 45/450",
        price: 45,
        image: "/chiv.gif",
      },
      {
        id: "chivas regal 12YO",
        nameKey: "ჩივას რეგალი",
        descriptionKey: "ვისკი 20/360",
        price: 20,
        image: "/chiv.gif",
      },
      {
        id: "John Walker ",
        nameKey: "John Walker",
        descriptionKey: "ვისკი 18/360",
        price: 18,
        image: "/joni.jpg",
      },
      {
        id: "John Walker Red",
        nameKey: "John Walker Red",
        descriptionKey: "ვისკი 16/320",
        price: 16,
        image: "/labe.jpg",
      },
      {
        id: "red-label",
        nameKey: "რედ ლეიბელი",
        descriptionKey: "ვისკი",
        price: 0,
        image: "/sp.jpg",
      },
      {
        id: "jameson",
        nameKey: "ჯეიმსონი",
        descriptionKey: "ვისკი 30/400",
        price: 30,
        image: "/jame.avif",
      },
      {
        id: "karva",
        nameKey: "ქარვა",
        descriptionKey: "ლუდი",
        price: 15,
        image: "/carva.jpg",
      },
      {
        id: "natakhtari",
        nameKey: "ნატახტარი",
        descriptionKey: "ლუდი",
        price: 12,
        image: "/nat.webp",
      },
      {
        id: "efes",
        nameKey: "ეფესი",
        descriptionKey: "ლუდი",
        price: 13,
        image: "/efesbeer330.webp",
      },
      {
        id: "heineken",
        nameKey: "ჰეინეკენი",
        descriptionKey: "ლუდი",
        price: 20,
        image: "/heineken.avif",
      },
      {
        id: "Koshken Korva",
        nameKey: "koshken",
        descriptionKey: "ალკოჰოლური სასმელი 0.5",
        price: 60,
        image: "/koshka.avif",
      },
      {
        id: "Koshken Korva 1l",
        nameKey: "koshken",
        descriptionKey: "ალკოჰოლური სასმელი 1",
        price: 60,
        image: "/koshka.avif",
      },
      {
        id: "Kirke",
        nameKey: "koshken",
        descriptionKey: "ალკოჰოლური სასმელი",
        price: 60,
        image: "/kir.avif",
      },
      {
        id: "estrela",
        nameKey: "estrella",
        descriptionKey: "ლუდი",
        price: 15,
        image: "/es.jpg",
      },
      {
        id: "Draft Beer",
        nameKey: "ჩამოსასხმელი ლუდი",
        descriptionKey: "ლუდი",
        price: 15,
        image: "/chamoasxi.jpg",
      },
      {
        id: "Erdinger",
        nameKey: "Erdinger",
        descriptionKey: "ლუდი",
        price: 15,
        image: "/erd.webp",
      },
    ],
    image: "/alcohol.png",
  },

  {
    id: "soups",
    nameKey: "წვნიანები",
    items: [
      {
        id: "chicken-soup",
        nameKey: "ქათმის წვნიანი",
        descriptionKey: "ქათმის ბულიონი",
        price: 15,
        image: "/unnamed.jpg",
      },
      {
        id: "mushroom-cream",
        nameKey: "სოკოს კრემსუპი",
        descriptionKey: "კრემოვანი სუპი",
        price: 18,
        image: "/soup.jpg",
      },
      {
        id: "mushroom-soup",
        nameKey: "სოკოს წვნიანი",
        descriptionKey: "სოკოს სუპი",
        price: 15,
        image: "/sokos_wvniani.jpg",
      },
      {
        id: "kharcho",
        nameKey: "ხარჩო",
        descriptionKey: "ქართული სუპი",
        price: 22,
        image: "/kharchos-recepti.webp",
      },
      {
        id: "chorba",
        nameKey: "ჩორბა",
        descriptionKey: "თურქული სუპი",
        price: 15,
        image: "/ჩორბა.avif",
      },
      {
        id: "yogurt-soup",
        nameKey: "მაწვნის სუპი",
        descriptionKey: "მსუბუქი სუპი",
        price: 10,
        image: "/matsvnis-supi.jpg",
      },

      {
        id: "akroshka",
        nameKey: "აკროშკა",
        price: 14,
        image: "/აკ.jpg",
      },
      {
        id: "chixirtma",
        nameKey: "ჩიხირთმა",
        descriptionKey: "მსუბუქი სუპი",
        price: 18,
        image: "/ჩიხ.webp",
      },
      {
        id: "xashlama",
        nameKey: "ხაშლამა",
        descriptionKey: "წვნიანი",
        price: 21,
        image: "/ხაშლამა.jpg",
      },
      {
        id: "uxa",
        nameKey: "უხა",
        descriptionKey: "წვნიანი",
        price: 16,
        image: "/უხა.webp",
      },
    ],
    image: "/soup.jpg",
  },

  {
    id: "salads",
    nameKey: "სალათები",
    items: [
      {
        id: "choban-salad",
        nameKey: "ჩობან სალათა",
        descriptionKey: "თურქული სალათა",
        price: 15,
        image: "/choban.jpg",
      },
      {
        id: "კიტრი პომიდვრის სალათა",
        nameKey: "კიტრი პომიდვრის სალათა",
        descriptionKey: "სალათა",
        image: "/კი.jpeg",
      },

      {
        id: "კიტრი პომიდვრის სალათა ნიგვზით",
        nameKey: "კიტრი პომიდვრის სალათა ნიგვზით",
        descriptionKey: "სალათა",
        price: 18,
        image: "/ნიგ.jpg",
      },
      {
        id: "მწვანე სალათა",
        nameKey: "მწვანე სალათა",
        descriptionKey: "სალათა",
        price: 15,
        image: "/მწ.webp",
      },
      {
        id: "kasik salata",
        nameKey: "კაში სალათა",
        descriptionKey: "სალათა",
        price: 15,
        image: "/2006.webp",
      },
      {
        id: "zetisxili",
        nameKey: "დაქუცმაცებული ზეთისხილი",
        descriptionKey: " სალათა",
        price: 15,
        image: "/oliv.jpg",
      },
      {
        id: "season-salad",
        nameKey: "სეზონური სალათა",
        descriptionKey: "ახალი ბოსტნეული",
        price: 15,
        image: "/sezon.jpg",
      },
      {
        id: "caesar-chicken",
        nameKey: "ცეზარის სალათა ქათმით",
        descriptionKey: "კლასიკური სალათა",
        price: 28,
        image: "/caesar.jpg",
      },
      {
        id: "caesar-shrimp",
        nameKey: "ცეზარის სალათა კრევეტით",
        descriptionKey: "კლასიკური სალათა",
        price: 44,
        image: "/caes.jpeg",
      },
      {
        id: "greek-salad",
        nameKey: "ბერძნული სალათა",
        descriptionKey: "კლასიკური სალათა",
        price: 44,
        image: "/grik.jpg",
      },
    ],
    image: "/salad.jpg",
  },

  {
    id: "cold-meals",
    nameKey: "ცივი კერძები",
    items: [
      {
        id: "green-bouqet",
        nameKey: "მწვანილის თაიგული",
        price: 15,
        image: "/ნწ.jpeg",
      },
      {
        id: "badrijani",
        nameKey: "ბადრიჯანი ნიგვზით",
        price: 16,
        image: "/nigvziani-badrijani.jpg",
      },
      {
        id: "turkish-cheese",
        nameKey: "თურქული ყველი",
        price: 16,
        image: "/turkche.jpg",
      },
      {
        id: "georgian-cheese",
        nameKey: "სულგუნი ყველი",
        price: 16,
        image: "/სულგუნი.jpg",
      },
      {
        id: "smoked-cheese",
        nameKey: "შებოლილი ყველი",
        price: 16,
        image: "/შებოლილი.jpg",
      },
      {
        id: "cheese-asort",
        nameKey: "ყველის ასორტი",
        price: 22,
        image: "/yveli.webp",
      },
      {
        id: "pickles-asort",
        nameKey: "მჟავის ასორტი",
        price: 12,
        image: "/pickles-1.webp",
      },
      {
        id: "phkhali-asort",
        nameKey: "ფხალის ასორტი",
        price: 28,
        image: "/unnamed (2).jpg",
      },
      { id: "kisir", nameKey: "კისირი", price: 15, image: "/kisir.jpg" },

      {
        id: "wawtermelon-melon",
        nameKey: "საზამთრო ნესვი",
        price: 35,
        image: "/melon.jpg",
      },
      {
        id: "carrot-yogurt",
        nameKey: "სტაფილოს იოგურტი",
        price: 15,
        image: "/kar.jpg",
      },
      {
        id: "europe-cheese",
        nameKey: "ევროპული ყველის ასორტი",
        price: 45,
        image: "/yvel.webp",
      },
    ],
    image: "/assorts.avif",
  },

  {
    id: "meat",
    nameKey: "ხორცეული",
    items: [
      {
        id: "liver-bbq",
        nameKey: "ჯიგრის მწვადი",
        price: 25,
        image: "/liver.jpg",
      },
      {
        id: "chkmeruli",
        nameKey: "ჩქმერული",
        price: 48,
        image: "/32.png",
      },
      {
        id: "kagit kebab",
        nameKey: "ქაღალდის ქაბაბი",
        price: 30,
        image: "/likas.jpg",
      },
      {
        id: "kazbasi kebab",
        nameKey: "ბატის თავის ქაბაბი",
        price: 40,
        image: "/kaz.jpeg",
      },
      {
        id: "sac kavurma",
        nameKey: "საკ შეწვა",
        price: 35,
        image: "/sac.webp",
      },
      {
        id: "tepsi kebab",
        nameKey: "უჯრა ქაბაბი",
        price: 30,
        image: "/kasd.jpeg",
      },
      {
        id: "sarma beyti",
        nameKey: "სარმას კუპლეტი",
        price: 35,
        image: "/sarma.jpeg",
      },

      {
        id: "lamb-bbq",
        nameKey: "ხბოს ნეკნი",
        price: 40,
        image: "/lamb.jpg",
      },
      {
        id: "Sheep-BBQ",
        nameKey: "ცხვრის მწვადი",
        price: 40,
        image: "/393.jpg",
      },
      {
        id: "lamb-ribs",
        nameKey: "ცხვრის ნეკნი",
        price: 40,
        image: "/lamb1.jpg",
      },
      {
        id: "adana-kebab",
        nameKey: "ადანა ქაბაბი",
        price: 35,
        image: "/adana.webp",
      },
      {
        id: "chicken-bbq",
        nameKey: "ქათმის მწვადი",
        price: 30,
        image: "/მწვადი.png",
      },
      {
        id: "chicken-wings",
        nameKey: "ქათმის ფრთები",
        price: 30,
        image: "/asda.webp",
      },
      {
        id: "smoked-lamb",
        nameKey: "ხბოს ჩაშუშული",
        price: 32,
        image: "/images.jpeg",
      },
      {
        id: "family-lamb",
        nameKey: "ხბოს ოჯახური",
        price: 28,
        image: "/ხბოჯახური.png",
      },
      {
        id: "tabaka-chick",
        nameKey: "ტაბაკა წიწილა",
        price: 27,
        image: "/chabaka.webp",
      },
      {
        id: "madam-bouvar",
        nameKey: "მადამ ბოვარი",
        price: 30,
        image: "/madam-bovaris-recepti.webp",
      },
      {
        id: "steak",
        nameKey: "სტეიკი სოკოს სოუსით",
        price: 35,
        image: "/steak.jpg",
      },
      {
        id: "Belen tava",
        nameKey: "ბელენ ტრეი",
        price: 40,
        image: "/belen.jpeg",
      },
      {
        id: "ribs-ajika",
        nameKey: "ნეკნი აჯიკაში",
        price: 80,
        image: "/აჯიკა.webp",
      },
      {
        id: "family-chicken",
        nameKey: "ოჯახური ქათმის",
        price: 20,
        image: "/ojakhuri.jpg",
      },
      {
        id: "sausage-desk",
        nameKey: "სოსისების დაფა",
        price: 70,
        image: "/7.jpg",
      },

      {
        id: "liver-withsauce",
        nameKey: "ღვიძლი საფანის სოუსით",
        price: 20,
        image: "/bjih.jpg",
      },

      {
        id: "kiev-coutlet",
        nameKey: "კიევური კატლეტი ფრით ან პიურით",
        price: 35,
        image: "/kiev.webp",
      },
      {
        id: "mixed-grill",
        nameKey: "შერეული გრილი",
        descriptionKey: "ქათამი + ხბო + ქაბაბი",
        price: 80,
        image: "/assorted-mix-grills-with-chicken-tikka-beef-kabab-mutton-kebab-wings-boti-malai-chop-shish-tawook-served-dish-isolated-background-top-view-arabic-food_689047-4724.avif",
      },
      {
        id: "kebab-pan",
        nameKey: "ჩაშლილი ქაბაბი კეცზე",
        price: 35,
        image: "/kebab.webp",
      },
    ],
    image: "/meat.jpg",
  },
  {
    id: "garnir",
    nameKey: "სნექები",
    items: [
      {
        id: "mashed potatoes",
        nameKey: "პიურე",
        price: 10,
        image: "/pou.jpg",
      },
      {
        id: "french-fries",
        nameKey: "ფრი",
        price: 15,
        image: "/fries.jpg",
      },
      {
        id: "mexican",
        nameKey: "მექსიკური კარტოფილი",
        price: 15,
        image: "/kartoili.jpg",
      },
      {
        id: "icli kofte",
        nameKey: "იჩლი კოფტე",
        price: 10,
        image: "/images22.jpeg",
      },
    ],
    image: "/fries.jpg",
  },
  {
    id: "pastry",
    nameKey: "ცომეული",
    items: [
      {
        id: "imerian-xaxhapuri",
        nameKey: "იმერული ხაჭაპური",
        price: 25,
        image: "/იმერული.webp",
      },
      {
        id: "Pizza Margarita",
        nameKey: "Pizza Margarita",
        price: 25,
        image: "/PIZZA-MARGHERITA.jpg",
      },
      {
        id: "Pizza Mix",
        nameKey: "Pizza Mix",
        price: 30,
        image: "/sliced-pizza.jpg",
      },
      {
        id: "Pizza Pepperoni",
        nameKey: "Pizza Pepperoni",
        price: 30,
        image: "/Quick-and-Easy-Pepperoni-Pizza-700x700.jpeg",
      },
      {
        id: "Pizza Vegeretarian",
        nameKey: "Pizza Vegeretarian",
        price: 25,
        image: "/kaio.jpeg",
      },
      {
        id: "Pizza Lahmanjun",
        nameKey: "Pizza Lahmanjun",
        price: 15,
        image: "/lahma.jpeg",
      },
      {
        id: "Megrelian-Xachapuri",
        nameKey: "მეგრული ხაჭაპური",
        price: 28,
        image: "/მეგ.webp",
      },
      {
        id: "Royal Khachapuri",
        nameKey: "სამეფო",
        price: 34,
        image: "/king.jpg",
      },
      {
        id: "adjarian",
        nameKey: "აჭარული ",
        price: 23,
        image: "/adjaruli+khachapuri.webp",
      },
      {
        id: "mchadi",
        nameKey: "მჭადი ",
        price: 10,
        image: "/images (2).jpeg",
      },
      {
        id: "lobiani",
        nameKey: "ლობიანი ",
        price: 18,
        image: "/lobiani-gnta.webp",
      },
    ],
    image: "/xach.jpg",
  },
  {
    id: "seafood",
    nameKey: "თევზეულობა",
    items: [
      {
        id: "Barabulka",
        nameKey: "Barabulka",
        price: 35,
        image: "/bar.webp",
      },
      {
        id: "Sibasi",
        nameKey: "sibasi",
        price: 48,
        image: "/sibas.jpg",
      },
      {
        id: "kalmaxi",
        nameKey: "კალმახი",
        price: 25,
        image: "/kiki.jpg",
      },
      {
        id: "Cooked Kalmaxi",
        nameKey: "კალმახი",
        price: 25,
        image: "/sewva.jpg",
      },
      {
        id: "Dorado",
        nameKey: "დორადო",
        price: 55,
        image: "/download (1).jpeg",
      },
      {
        id: "fish-desk",
        nameKey: "ზღვის პროდუქტების დაფა",
        price: 190,
        image: "/desk-fish.jpg",
      },
      {
        id: "shrimp",
        nameKey: "კრევეტი",
        price: 40,
        image: "/sh.jpg",
      },
      {
        id: "kalmari",
        nameKey: "კალმარი",
        price: 35,
        image: "/kalm.jpg",
      },
    ],
    image: "/shrimps.jpg",
  },
  {
    id: "desserts",
    nameKey: "დესერტები",
    items: [
      {
        id: "fruit-asort",
        nameKey: "ხილის ასორტი",
        price: 20,
        image: "/fara.jpg",
      },
      {
        id: "watermelon-melon",
        nameKey: "ხილის ასორტი",
        price: 30,
        image: "/kala.jpeg",
      },
      {
        id: "Kurnefe",
        nameKey: "კურნეფე",
        price: 25,
        image: "/kunefe.jpg",
      },
      {
        id: "ნაყინი",
        nameKey: "დესერტი",
        price: 15,
        image: "/nayini.jpg",
      },
      {
        id: "ხილის ასორტი დიდი",
        nameKey: "დესერტი",
        price: 45,
        image: "/asort.jpg",
      },
      {
        id: "ხილის ასორტი პატარა",
        nameKey: "დესერტი",
        price: 25,
        image: "/asort.jpg",
      },
      {
        id: "Cheese cake",
        nameKey: "დესერტი",
        price: 15,
        image: "/ch.jpeg",
      },
      {
        id: "Tiramisu",
        nameKey: "tiramisu",
        price: 15,
        image: "/tir.jpg",
      },
      {
        id: "Baklava 3pcs",
        nameKey: "baklava",
        price: 25,
        image: "/baki.jpeg",
      },
      {
        id: "Magnolia",
        nameKey: "magnolia",
        price: 15,
        image: "/mag.jpeg",
      },
    ],
    image: "/alpen.jpg",
  },
  {
    id: "meze",
    nameKey: "აპეტაიზერი",
    items: [
      {
        id: "orshtorvis-plate",
        nameKey: "ორშტორვის თეფში",
        price: 25,
        image: "/images (1).jpeg",
      },
      {
        id: "atom",
        nameKey: "ატომი",
        price: 15,
        image: "/atom.webp",
      },
      {
        id: "cacik",
        nameKey: "ჯაჯიკი",
        price: 15,
        image: "/caca.jpg",
      },
      {
        id: "acili ezme",
        nameKey: "აჯილი ეზმე",
        price: 15,
        image: "/acili.jpg",
      },
      {
        id: "strained yougurt",
        nameKey: "გაფილტრული იოგურტი",
        price: 15,
        image: "/str.jpg",
      },
      {
        id: "aleppo homs",
        nameKey: "ალეპო ჰომს",
        price: 15,
        image: "/allepo.webp",
      },
      {
        id: "hummus with olive oil",
        nameKey: "ჰუმუსი ზეითუნის ზეთით",
        price: 15,
        image: "/hum.jpg",
      },
      {
        id: "hummus with butter",
        nameKey: "ჰუმუსი კარაქით",
        price: 20,
        image: "/humb.jpg",
      },
      {
        id: "alinazik",
        nameKey: "ალინაზიკი",
        price: 20,
        image: "/ali.jpeg",
      },
      {
        id: "thyme salad zaatar",
        nameKey: "თიმის სალათა",
        price: 20,
        image: "/ზატ.jpeg",
      },
      {
        id: "Babagannuc",
        nameKey: "ბაბაგანუჩი",
        price: 15,
        image: "/ბაბა.webp",
      },
      {
        id: "eggplant yogurt",
        nameKey: "ბადრიჯნის იოგურტი",
        price: 15,
        image: "/egg.jpg",
      },
      {
        id: "olive salad",
        nameKey: "ზეთის ხილის სალათა",
        price: 15,
        image: "/oli.jpeg",
      },
      {
        id: "pepper yogurt",
        nameKey: "წიწაკის იოგურტი",
        price: 15,
        image: "/images5.jpeg",
      },
      {
        id: "cig kofte",
        nameKey: "უმი ხორცის ბურთულები",
        price: 25,
        image: "/cig.jpg",
      },
    ],
    image: "/meze.jpeg",
  },
  {
    id: "sefme-kavalte",
    nameKey: "საუზმე",
    items: [],
    image: "/sauzme.webp",
  },
];
