import { Category } from "../types/menuitems";
// kalmaxi
// dorado
// sibasi
// barabuli
// soko sulgunit
// bostneuli dafaze

export const menu: Category[] = [
  {
    id: "drinks",
    nameKey: "სასმელები",
    items: [
      {
        id: "raspberry-lemonade",
        nameKey: "მალინის ლიმონათი",
        descriptionKey: "სახლის ლიმონათი მალინით",
        image: "/images (3).jpeg",
        price: 5,
      },
      {
        id: "energy-drink",
        nameKey: "ენერგეტიკული სასმელი",
        image: "/hek.jpg",
        price: 4,
      },
      {
        id: "strawberry-lemonade",
        nameKey: "მარწყვის ლიმონათი",
        descriptionKey: "სახლის ლიმონათი მარწყვით და ლიმონით",
        image: "/ma.webp",
        price: 5,
      },
      {
        id: "watermelon-lemonade",
        nameKey: "საზამთროს ლიმონათი",
        descriptionKey: "ახალი საზამთროს ლიმონათი",
        image: "/wat.jpg",
        price: 6,
      },
      {
        id: "mint-lemonade",
        nameKey: "პიტნის ლიმონათი",
        descriptionKey: "გამაგრილებელი ლიმონათი პიტნით და ლიმონით",
        image: "/mint.jpg",
        price: 4,
      },
      {
        id: "cold-coffee",
        nameKey: "ცივი ყავა",
        descriptionKey: "გამაგრილებელი ცივი ყავა",
        image: "/civi.jpg",
        price: 4,
      },
      {
        id: "cappuccino",
        nameKey: "კაპუჩინო",
        descriptionKey: "ყავის სახეობა",
        image: "/cap.jpg",
        price: 4,
      },
      {
        id: "americano",
        nameKey: "ამერიკანო",
        descriptionKey: "ყავის სახეობა",
        image: "/americano12.jpg",
        price: 4,
      },
      {
        id: "latte",
        nameKey: "ლატე",
        descriptionKey: "ყავის სახეობა",
        image: "/late.webp",
        price: 4,
      },
      {
        id: "espresso",
        nameKey: "ესპრესო",
        descriptionKey: "ძლიერი ყავა",
        image: "/esp.webp",
        price: 4,
      },
    ],
    image: "/coc.webp",
  },

  {
    id: "sauces",
    nameKey: "სოუსები",
    items: [
      {
        id: "tyemali",
        nameKey: "ტყემალი",
        descriptionKey: "ქართული ტრადიციული სოუსი",
        image: "/tyemali_w_h.jpeg",
        price: 5,
      },
      {
        id: "satsebeli",
        nameKey: "საწებელი",
        descriptionKey: "ქართული ტრადიციული სოუსი",
        image: "/satsebeli.jpeg",
        price: 5,
      },
      {
        id: "adjika",
        nameKey: "აჯიკა",
        descriptionKey: "ცხარე ქართული სოუსი",
        image: "/adjika.jpeg",
        price: 5,
      },
      {
        id: "ketchup",
        nameKey: "კეტჩუპი",
        descriptionKey: "ტომატის სოუსი",
        image: "/ketchup.jpg",
        price: 5,
      },
      {
        id: "mayonnaise",
        nameKey: "მაიონეზი",
        descriptionKey: "კრემოვანი სოუსი",
        image: "/maio.webp",
        price: 5,
      },
      {
        id: "baje",
        nameKey: "ბაჟე",
        descriptionKey: "კაკლის ქართული სოუსი",
        image: "/90.jpg",
        price: 10,
      },
      {
        id: "barbecue-sauce",
        nameKey: "ბარბექიუს სოუსი",
        descriptionKey: "ტკბილ-შებოლილი სოუსი",
        image: "/bbq.jpg",
        price: 7,
      },
      {
        id: "nasharab",
        nameKey: "ნაშარაბი",
        descriptionKey: "ბროწეულის სოუსი",
        image: "/medium.webp",
        price: 7,
      },
    ],
    image: "/sauce.jpeg",
  },

  {
    id: "alcohol",
    nameKey: "ალკოჰოლური სასმელები",
    items: [
      {
        id: "chacha",
        nameKey: "ჭაჭა",
        descriptionKey: "ქართული ალკოჰოლური სასმელი",
        price: 0,
        image: "",
      },
      {
        id: "chacha-peach",
        nameKey: "ჭაჭა ატმის",
        descriptionKey: "ატმის არაყი",
        price: 0,
        image: "",
      },
      {
        id: "chacha-honey",
        nameKey: "ჭაჭა თაფლის",
        descriptionKey: "თაფლის არაყი",
        price: 0,
        image: "",
      },
      {
        id: "absolute",
        nameKey: "აბსოლუტი",
        descriptionKey: "ვოდკა",
        price: 0,
        image: "/baba.jpg",
      },
      {
        id: "nemiroff",
        nameKey: "ნემიროფი",
        descriptionKey: "ვოდკა",
        price: 0,
        image: "/nem.jpeg",
      },
      {
        id: "finlandia",
        nameKey: "ფინლანდია",
        descriptionKey: "ვოდკა",
        price: 0,
        image: "/fin.webp",
      },
      {
        id: "raki",
        nameKey: "რაქი",
        descriptionKey: "თურქული სასმელი",
        price: 0,
        image: "/raki.webp",
      },
      {
        id: "efes-gold",
        nameKey: "ეფესი გოლდი",
        descriptionKey: "ლუდი",
        price: 0,
        image: "/ასდა.avif",
      },
      {
        id: "whisky",
        nameKey: "ვისკი",
        descriptionKey: "ალკოჰოლური სასმელი",
        price: 0,
        image: "/whi.jpg",
      },
      {
        id: "jack-daniels",
        nameKey: "ჯეკ დენიელსი",
        descriptionKey: "ვისკი",
        price: 0,
        image: "/jak.webp",
      },
      {
        id: "chivas-regal",
        nameKey: "ჩივას რეგალი",
        descriptionKey: "ვისკი",
        price: 0,
        image: "/chiv.gif",
      },
      {
        id: "red-label",
        nameKey: "რედ ლეიბელი",
        descriptionKey: "ვისკი",
        price: 0,
        image: "/sp.jpg",
      },
      {
        id: "jameson",
        nameKey: "ჯეიმსონი",
        descriptionKey: "ვისკი",
        price: 0,
        image: "/jame.avif",
      },
      {
        id: "karva",
        nameKey: "ქარვა",
        descriptionKey: "ლუდი",
        price: 10,
        image: "/carva.jpg",
      },
      {
        id: "natakhtari",
        nameKey: "ნატახტარი",
        descriptionKey: "ლუდი",
        price: 12,
        image: "/nat.webp",
      },
      {
        id: "efes",
        nameKey: "ეფესი",
        descriptionKey: "ლუდი",
        price: 13,
        image: "/efesbeer330.webp",
      },
      {
        id: "heineken",
        nameKey: "ჰეინეკენი",
        descriptionKey: "ლუდი",
        price: 15,
        image: "/heineken.avif",
      },
      {
        id: "corona",
        nameKey: "კორონა",
        descriptionKey: "ლუდი",
        price: 15,
        image: "/corona.png",
      },
      {
        id: "draft-beer",
        nameKey: "ჩამოსასხმელი ლუდი",
        descriptionKey: "ლუდი",
        price: 15,
        image: "",
      },
    ],
    image: "/alcohol.png",
  },

  {
    id: "soups",
    nameKey: "წვნიანები",
    items: [
      {
        id: "chicken-soup",
        nameKey: "ქათმის წვნიანი",
        descriptionKey: "ქათმის ბულიონი",
        price: 15,
        image: "/unnamed.jpg",
      },
      {
        id: "mushroom-cream",
        nameKey: "სოკოს კრემსუპი",
        descriptionKey: "კრემოვანი სუპი",
        price: 18,
        image: "/soup.jpg",
      },
      {
        id: "mushroom-soup",
        nameKey: "სოკოს წვნიანი",
        descriptionKey: "სოკოს სუპი",
        price: 15,
        image: "/sokos_wvniani.jpg",
      },
      {
        id: "kharcho",
        nameKey: "ხარჩო",
        descriptionKey: "ქართული სუპი",
        price: 22,
        image: "/kharchos-recepti.webp",
      },
      {
        id: "lentil-soup",
        nameKey: "ოსპის სუპი",
        descriptionKey: "თურქული სუპი",
        price: 15,
        image: "/ოსპი.jpg",
      },
      {
        id: "ishkembe",
        nameKey: "იშკემბე",
        descriptionKey: "თურქული სუპი",
        price: 20,
        image: "",
      },
      {
        id: "chorba",
        nameKey: "ჩორბა",
        descriptionKey: "თურქული სუპი",
        price: 15,
        image: "/ჩორბა.avif",
      },
      {
        id: "yogurt-soup",
        nameKey: "მაწვნის სუპი",
        descriptionKey: "მსუბუქი სუპი",
        price: 10,
        image: "/matsvnis-supi.jpg",
      },
      {
        id: "atom",
        nameKey: "ატომი",
        descriptionKey: "მსუბუქი სუპი",
        price: 15,
        image: "/atom.webp",
      },
    ],
    image: "/soup.jpg",
  },

  {
    id: "salads",
    nameKey: "სალათები",
    items: [
      {
        id: "choban-salad",
        nameKey: "ჩობან სალათა",
        descriptionKey: "თურქული სალათა",
        price: 15,
        image: "/chobam.jpg",
      },
      {
        id: "zetisxili",
        nameKey: "დაქუცმაცებული ზეთისხილი",
        descriptionKey: " სალათა",
        price: 15,
        image: "/oliv.jpg",
      },
      {
        id: "season-salad",
        nameKey: "სეზონური სალათა",
        descriptionKey: "ახალი ბოსტნეული",
        price: 15,
        image: "/sezon.jpg",
      },
      {
        id: "caesar-chicken",
        nameKey: "ცეზარის სალათა ქათმით",
        descriptionKey: "კლასიკური სალათა",
        price: 28,
        image: "/caesar.jpg",
      },
      {
        id: "caesar-shrimp",
        nameKey: "ცეზარის სალათა კრევეტით",
        descriptionKey: "კლასიკური სალათა",
        price: 44,
        image: "/caes.jpeg",
      },
      {
        id: "greek-salad",
        nameKey: "ბერძნული სალათა",
        descriptionKey: "კლასიკური სალათა",
        price: 44,
        image: "/grik.jpg",
      },
    ],
    image: "/salad.jpg",
  },

  {
    id: "asorts",
    nameKey: "ასორტი",
    items: [
      {
        id: "cheese-asort",
        nameKey: "ყველის ასორტი",
        price: 22,
        image: "/yveli.webp",
      },
      {
        id: "pickles-asort",
        nameKey: "მჟავის ასორტი",
        price: 12,
        image: "/pickles-1.webp",
      },
      {
        id: "phkhali-asort",
        nameKey: "ფხალის ასორტი",
        price: 28,
        image: "/unnamed (2).jpg",
      },
      { id: "kisir", nameKey: "კისირი", price: 15, image: "/kisir.jpg" },
      {
        id: "fruit-asort",
        nameKey: "ხილის ასორტი",
        price: 15,
        image: "/asort.jpg",
      },
      {
        id: "wawtermelon-melon",
        nameKey: "საზამთრო ნესვი",
        price: 15,
        image: "/melon.jpg",
      },
      {
        id: "carrot-yogurt",
        nameKey: "სტაფილოს იოგურტი",
        price: 15,
        image: "/kar.jpg",
      },
      {
        id: "europe-cheese",
        nameKey: "ევროპული ყველის ასორტი",
        price: 45,
        image: "/yvel.webp",
      },
    ],
    image: "/assorts.avif",
  },

  {
    id: "meat",
    nameKey: "ხორცეული",
    items: [
      {
        id: "liver-bbq",
        nameKey: "ჯიგრის მწვადი",
        price: 25,
        image: "/liver.jpg",
      },
      {
        id: "kalmaxi",
        nameKey: "კალმახი",
        price: 25,
        image: "/capture.png",
      },
      {
        id: "dorado",
        nameKey: "დორადო",
        price: 25,
        image: "/download (1).jpeg",
      },
      {
        id: "lamb-bbq",
        nameKey: "ცხვრის მწვადი",
        price: 40,
        image: "/lamb.jpg",
      },
      {
        id: "lamb-ribs",
        nameKey: "ცხვრის ნეკნი",
        price: 40,
        image: "/lamb1.jpg",
      },
      {
        id: "adana-kebab",
        nameKey: "ადანა ქაბაბი",
        price: 35,
        image: "/adana.webp",
      },
      {
        id: "chicken-bbq",
        nameKey: "ქათმის მწვადი",
        price: 30,
        image: "/მწვადი.png",
      },
      {
        id: "chicken-wings",
        nameKey: "ქათმის ფრთები",
        price: 30,
        image: "/asda.webp",
      },
      {
        id: "smoked-lamb",
        nameKey: "ხბოს ჩაშუშული",
        price: 32,
        image: "/images.jpeg",
      },
      {
        id: "family-lamb",
        nameKey: "ხბოს ოჯახური",
        price: 28,
        image: "/ხბოჯახური.png",
      },
      {
        id: "salkhino",
        nameKey: "სალხინო",
        price: 42,
        image: "",
      },
      {
        id: "chabaka-chick",
        nameKey: "ჭაბაკა წიწილა",
        price: 27,
        image: "/chabaka.webp",
      },
      {
        id: "madam-bouvar",
        nameKey: "მადამ ბოვარი",
        price: 30,
        image: "/madam-bovaris-recepti.webp",
      },
      {
        id: "steak",
        nameKey: "სტეიკი სოკოს სოუსით",
        price: 35,
        image: "/steak.jpg",
      },
      {
        id: "beef-steak",
        nameKey: "საქონლის სტეიკი",
        price: 115,
        image: "/Beef-Steaf.webp",
      },
      {
        id: "ribs-ajika",
        nameKey: "ნეკნი აჯიკაში",
        price: 115,
        image: "/აჯიკა.webp",
      },
      {
        id: "family-chicken",
        nameKey: "ოჯახური ქათმის",
        price: 20,
        image: "/ojakhuri.jpg",
      },
      {
        id: "sausage-desk",
        nameKey: "სოსისების დაფა",
        price: 20,
        image: "/7.jpg",
      },
      {
        id: "fish-desk",
        nameKey: "ზღვის პროდუქტების დაფა",
        price: 190,
        image: "/desk-fish.jpg",
      },
      {
        id: "liver-withsauce",
        nameKey: "ღვიძლი საფანის სოუსით",
        price: 20,
        image: "",
      },
      {
        id: "raw-beef1",
        nameKey: "უმი ხორცის ბურთულები",
        price: 25,
        image: "/unnamed-file-16.jpg",
      },
      {
        id: "orshtorvis-plate",
        nameKey: "ორშტორვის თეფში",
        price: 25,
        image: "/images (1).jpeg",
      },
      {
        id: "kiev-coutlet",
        nameKey: "კიევური კატლეტი ფრით ან პიურით",
        price: 35,
        image: "/kiev.webp",
      },
      {
        id: "mixed-grill",
        nameKey: "შერეული გრილი",
        descriptionKey: "ქათამი + ხბო + ქაბაბი",
        price: 80,
        image: "/maxresdefault.jpg",
      },
      {
        id: "kebab-pan",
        nameKey: "ჩაშლილი ქაბაბი კეცზე",
        price: 35,
        image: "/kebab.webp",
      },
      { id: "shrimp", nameKey: "კრევეტი", price: 40, image: "/shrimps.jpg" },
    ],
    image: "/meat.jpg",
  },
  {
    id: "snacks",
    nameKey: "სნექები",
    items: [
      {
        id: "french-fries",
        nameKey: "ფრი",
        price: 10,
        image: "/fries.jpg",
      },
      {
        id: "mexican",
        nameKey: "მექსიკური კარტოფილი",
        price: 15,
        image: "/kartoili.jpg",
      },
      {
        id: "turkish-cheese",
        nameKey: "თურქული ყველი",
        price: 16,
        image: "/turkche.jpg",
      },
      {
        id: "georgian-cheese",
        nameKey: "სულგუნი ყველი",
        price: 16,
        image: "/სულგუნი.jpg",
      },
      {
        id: "smoked-cheese",
        nameKey: "შებოლილი ყველი",
        price: 16,
        image: "/შებოლილი.jpg",
      },
      {
        id: "fkhali-asorti",
        nameKey: "ფხალის ასორტი",
        price: 28,
        image: "/ლი.jpg",
      },
      {
        id: "green-bouqet",
        nameKey: "მწვანილის თაიგული",
        price: 15,
        image: "",
      },
      {
        id: "badrijani",
        nameKey: "ბადრიჯანი ნიგვზით",
        price: 16,
        image: "/nigvziani-badrijani.jpg",
      },
    ],
    image: "/fries.jpg",
  },
  {
    id: "pastry",
    nameKey: "ცომეული",
    items: [
      {
        id: "carbonnara",
        nameKey: "კარბონარა",
        price: 25,
        image: "/photo.jpg",
      },
      {
        id: "penne-arabica",
        nameKey: "პენე არაბიკა",
        price: 23,
        image: "/penne.webp",
      },
      {
        id: "bolonezaa",
        nameKey: "ბოლონეზა",
        price: 25,
        image: "/bolo.jpg",
      },
      {
        id: "4cheese",
        nameKey: "4 ყველით",
        price: 32,
        image: "/4.jpg",
      },
      {
        id: "imerian-xaxhapuri",
        nameKey: "იმერული ხაჭაპური",
        price: 25,
        image: "/იმერული.webp",
      },
      {
        id: "megrelian-xaxhapuri",
        nameKey: "მეგრული ხაჭაპური",
        price: 28,
        image: "/მეგ.webp",
      },
      {
        id: "royal",
        nameKey: "სამეფო",
        price: 34,
        image: "",
      },
      {
        id: "adjarian",
        nameKey: "აჭარული ",
        price: 23,
        image: "/adjaruli+khachapuri.webp",
      },
      {
        id: "mchadi",
        nameKey: "მჭადი ",
        price: 10,
        image: "/images (2).jpeg",
      },
      {
        id: "lobiani",
        nameKey: "ლობიანი ",
        price: 18,
        image: "/lobiani-gnta.webp",
      },
      {
        id: "kretian-cheece",
        nameKey: "კრეტული ყველის პასტა",
        price: 15,
        image: "/kretian.avif",
      },
    ],
    image: "/xach.jpg",
  },
];
